apiVersion: apps/v1
kind: Deployment
metadata:
  name: lrjmpzzl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lrjmpzzl
  template:
    metadata:
      labels:
        app: lrjmpzzl
    spec:
      containers:
      - image: okteto.dev/lrjmpzzl:latest
        name: lrjmpzzl
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "6d736db4-6211-469a-b7fe-010bb0e29431"
        - name: Vless_Path
          value: "/6d736db4-6211-469a-b7fe-010bb0e29431"
        - name: Vmess_UUID
          value: "82d57390-2cb0-4815-ab13-69515b281cd1"
        - name: Vmess_Path
          value: "/82d57390-2cb0-4815-ab13-69515b281cd1"
        - name: Share_Path
          value: "/v2link"
